#!/bin/bash

# Reset text to normal
r=$(tput sgr0)

# Make text bold, blue background, and wline foreground
stars=$(tput bold; tput setab 4; tput setaf 7)

# Reset text, rline background, rline foreground
rline=$(tput sgr0; tput setab 1; tput setaf 1)

# Reset text, wline background, wline foreground
wline=$(tput sgr0; tput setab 7; tput setaf 7)

# Print. Just saving some line space
p() {
 echo -e "${@}"
}

# Could make lines functions, but this view is more readable
echo
p "${r}  ${stars} * * * * * * * * * * ${rline}███████████████████████████████"
p "${r}  ${stars}  * * * * * * * * *  ${wline}███████████████████████████████"
p "${r}  ${stars} * * * * * * * * * * ${rline}███████████████████████████████"
p "${r}  ${stars}  * * * * * * * * *  ${wline}███████████████████████████████"
p "${r}  ${stars} * * * * * * * * * * ${rline}███████████████████████████████"
p "${r}  ${stars}  * * * * * * * * *  ${wline}███████████████████████████████"
p "${r}  ${stars} * * * * * * * * * * ${rline}███████████████████████████████"
p "${r}  ${wline} ███████████████████████████████████████████████████"
p "${r}  ${rline} ███████████████████████████████████████████████████"
p "${r}  ${wline} ███████████████████████████████████████████████████"
p "${r}  ${rline} ███████████████████████████████████████████████████"
p "${r}  ${wline} ███████████████████████████████████████████████████"
p "${r}  ${rline} ███████████████████████████████████████████████████"
echo 
